name: CI Python Project

on:
  workflow_dispatch:
    inputs:
      TARGE_ENVIRONMENT:
        type: environment
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGE_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          #pip install -r requirements.txt

      - name: Run build step (if any)
        run: echo "Python build step (optional)"

      - name: Upload Python artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: python-build
          path: .  # Adjust to specific files if needed

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/  # Adjust path as needed

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Python artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: python-build
          path: staging

      - name: List downloaded files
        run: ls staging

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Deployment Step
        run: |
          echo "Deploying Python application..."
          echo "Environment: ${{ inputs.TARGE_ENVIRONMENT }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"
